server {
    listen 80;
    listen [::]:80;
    server_name __DOMAIN__;
    root __ROOT__;
    index index.html;
    location /.well-known/acme-challenge/ { try_files $uri =404; }
    location = /__ENTRY__ { default_type text/html; try_files $uri =404; }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name __DOMAIN__;
    root __ROOT__;
    index index.html;
    ssl_certificate __CERT_DIR__/config/live/__DOMAIN__/fullchain.pem;
    ssl_certificate_key __CERT_DIR__/config/live/__DOMAIN__/privkey.pem;
    location = /__ENTRY__ { default_type text/html; try_files $uri =404; }
    location / { try_files $uri $uri/ /index.html; }
}
