server {
    listen 80;
    listen [::]:80;
    server_name __DOMAIN__;
    root __ROOT__;
    index index.html;

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location = /__ENTRY__ {
        default_type text/html;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
